### PR TITLE
fix: Eye-pleasing translation changes

### PR DESCRIPTION
**Pull request by rustzz**
Grammar mistake: "Rotate" == "Вращать".
Not "Около". Correct: "Информация" or "О приложении".

### CODE REVIEW

**Comment by redwarp** [comment]
@rustzz I handle the translations through POEditor, see the https://github.com/redwarp/gif-wallpaper#translations
Do you want to update it over there, or do you want to take care of it?

And thanks!

**Comment by rustzz** [comment]
Please, confirm my request

**Comment by redwarp** [comment]
Okay just did! Thanks!

**Comment by rustzz** [comment]
indicated changes in this service

**Comment by redwarp** [comment]
@rustzz currently releasing a new version, it will be released as soon as Google approves. (takes also some times for F-droid)

**Comment by redwarp** [comment]
@rustzz sorry to bother you again, I added a few strings to translate, for a new feature : battery saving (it will pause the gif when the phone is in low battery mode)
Could you take a look and translate them? Thanks!

**Comment by rustzz** [comment]
Thanks for waiting for my answer. After receiving the update, I checked the translation and layout. The translation is correct.

But due to the different line sizes, some buttons wrap words and this does not look aesthetically pleasing.
For example, check the start page in Russian, where the "Activate" button is located.

**Pull request closed without merging**
